### ISSUE TITLE
Requires Google Play Services v13 or higher

### ISSUE THREAD

**Issue by MrHappy** [RikkaW/YASNAC#10]
When I run it, it gives this error...
Other safetynet app works fine.
I'm running LineageOS 18.1.

**Comment by RikkaW** [comment]
> On devices running Google Play Services v13.0 and above, the SafetyNet Attestation API also supports app-restricted API keys. This feature reduces the risk of accidental or unauthorized usage of quota-restricted API keys.

https://developer.android.com/training/safetynet/attestation

SafetyNet requires quota-restricted API key. I believe that in production environment, everyone should use this to avoid unauthorized usage.

**Comment by MrHappy** [comment]
@RikkaW I do not understand how that explains the message I get when I run 'run safetynet attestation'.
I thought I could install and run it.
According to the Google Playstore app I have the most recent version.

**Comment by pholcroft** [comment]
I do not understand the response or why this was closed. I too have the same error.

@RikkaW please can you explain in a different way why you have closed this and what the issue is, because we do not understand what you have written.

**Comment by RikkaW** [comment]
https://github.com/RikkaW/YASNAC/blob/012df809dfebdb354ada3edbf234ec3628eecc6a/app/src/main/java/rikka/safetynetchecker/main/MainViewModel.kt#L45-L48

"Requires Google Play Services v13 or higher" is from here. This check uses API from Play Service, so unless the API is broken, it means the version of installed Google Play Services is below v13.

**Comment by MrHappy** [comment]
I have version 21.48.57 (150400-424705839) running. Seems way higher than 13...
What's wrong?

**Comment by RikkaW** [comment]
@MrHappy Is Google Play Service preinstalled as a system app on your device? If not and your devices runs Android 11+, other user apps cannot access Google Play Service by default.

**Comment by MrHappy** [comment]
@RikkaW I have LineageOS 18.1 installed and MindTheGApps afterwards. My guess is other apps might not be able to access GPS.
Shouldn't other safetynet-checkers have the same issue?
How can I have yasnac access GPS?
