### ISSUE TITLE
Google play services API error 13:error

### ISSUE THREAD

**Issue by coMango** [RikkaW/YASNAC#13]
Hello. Running LineageOS 18.1 with Microg and magisk preflashed. Upon running YASNAC, the second box contains "Google Play Services API error 13:ERROR".

What might be causing this?

**Comment by RikkaW** [comment]
"Google Play Services API error 13:ERROR" is an error returned from Google Play Services (or microG in your case).
The implementation of YASNAC follows Google's documentation, nothing special is done. It works well with official Google Play Services.
You should ask the developer of microG for help.

**Comment by etam** [comment]
@coMango you must enable device registration
