### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by BaHeK1994** [RikkaW/YASNAC#14]
Video: https://disk.yandex.ru/i/k-RVeXDYVvN03Q

System info:
Phone: Xiaomi Mi 8
OS: Android 10
MIUI: 12

**Comment by RikkaW** [comment]
The stack trace shows that the crash happened in Play Service SDK, this means it's not our problem and nothing we can do.

**Comment by BaHeK1994** [comment]
Deleted all google play services data, the error is gone, thanks.
