### ISSUE TITLE
Error - Requires Googe Play Services v13.0

### ISSUE THREAD

**Issue by Sekt0rX** [RikkaW/YASNAC#22]
Hi, YASNAC was working fine until the recent update where I get "Requires Googe Play Services v13.0" error. 
Just wanting to confirm whether this is a bug or this is an issue on my end.

YASNAC itself shows Google Play Services version = 22.09.20 
Which is correct and it's the latest version available for my Galaxy S10 (Play Store shows it updated on 17 March 2022).

Device details:
Model - SM-G973F (beyond1lte)
Android Version - 11 (API 30)
Security Patch level - 2021-12-05

**Comment by RikkaW** [comment]
https://github.com/RikkaW/YASNAC/blob/4aeb22d1c25b026419db75767dbf78e986ccae53/app/src/main/java/rikka/safetynetchecker/main/MainViewModel.kt#L47-L50

The error is from here. It uses Google Play Services API directly, the internal is unknown. So, it should be a problem of Play service.

This build (https://github.com/RikkaW/YASNAC/actions/runs/2063107407) shows the detailed failure reason of `isGooglePlayServicesAvailable`, please try.

**Comment by Sekt0rX** [comment]
ah, I probably should have mentioned I'm running LineageOS (18.1) with MindtheGapps.
The error is "The version of Google Play services installed on the device is not authentic".

It's interesting to me because no other app or anything ever seems to pick it up, e.g. Google Play Store/Play Protect certification shows 'Device is certified'.

**Comment by RikkaW** [comment]
YASNAC follows the document from Google, nothing else is done. Maybe newer Google Play Service SDK adds some verification step, or Play Store is special. (These are only guesses)

**Comment by DealsBeam** [comment]
I'm having the same issue
lineageos 18.1
mindthegapps

**Comment by RikkaW** [comment]
@Sekt0rX https://github.com/RikkaW/YASNAC/issues/24#issuecomment-1087629607

**Comment by Sekt0rX** [comment]
Thanks, I can confirm installing via Google Play works without error.
