### ISSUE TITLE
"Something went wrong: The version of the Google Play services installed on this device is not authentic"

### ISSUE THREAD

**Issue by DealsBeam** [RikkaW/YASNAC#24]
I'm getting this error with the latest release of YASNAC

With YASNAC v1.1.3, I was getting "Requires Google Play Services v13.0 and above" error, even though my Google Play services is v22

Device: Pixel 2 XL
OS: Lineage OS 18.1 based on Android 11 ([XDA](https://forum.xda-developers.com/t/rom-official-lineage-os-18-1-for-pixel-2-2-xl.4165919/))

**Comment by RikkaW** [comment]
Duplicate #22

**Comment by DealsBeam** [comment]
I fixed it by installing YASNAC from Play store
