### ISSUE TITLE
Google Play Services API error 13: ERROR

### ISSUE THREAD

**Issue by cmonty14** [RikkaW/YASNAC#29]
Hello,
I installed YASNAC from Aurora Store, there was no error during installation.

However, when I start YASNAC I get this message:
Google Play Services API error 13: ERROR
![Screenshot_20220525-141457_Yet Another SafetyNet Attestation Checker](https://user-images.githubusercontent.com/12523591/170261350-5281332a-6405-475c-9e28-b53641da2c22.png)

Can you please advise how to fix this issue?

**Comment by Displax** [comment]
MicroG is not supported.

**Comment by etam** [comment]
@cmonty14 you must enable device registration
