### ISSUE TITLE
Releasing the app on F-Droid

### ISSUE THREAD

**Issue by Jowat97** [RikkaW/YASNAC#3]
Hello there!

Since this app is now also released under MIT license, it would be great to have it on F-Droid as well.
There is no Safetynet-Check on F-Droid at all and having a lightweight and open-source check like this one would be amazing.

Cheers!

**Comment by RikkaW** [comment]
Hi, the application requires an API key of SafetyNet and key is protected by the app's signature. Third-party build is not supported because of this.

**Comment by proletarius101** [comment]
> Hi, the application requires an API key of SafetyNet and key is protected by the app's signature. Third-party build is not supported because of this.

Definitely you don't need to provide the key to us. Just need to accept redistribution of your code.

**Comment by muelli** [comment]
> Definitely you don't need to provide the key to us.

would F-Droid then acquire a Google API key on their own?

**Comment by rollingmoai** [comment]
Available in the IzzyDroid repo:
https://android.izzysoft.de/repo/apk/rikka.safetynetchecker
