### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by pokurt** [RikkaW/YASNAC#8]
Hi, we have been getting `Google Play Services API error 7: NETWORK_ERROR` from YASNAC
![Screenshot_2022-01-30-09-19-56-779_rikka safetynetchecker](https://user-images.githubusercontent.com/43902347/151686476-6cefd077-4060-46d3-aef5-21363c681aad.jpg)

but here is a screenshot from safetynet check by sebastiang
![IMG_20220130_092037_893](https://user-images.githubusercontent.com/43902347/151686491-ba729c07-61f8-4a83-b081-d2edfcd6c3f0.jpg)

**Comment by RikkaW** [comment]
API quota exceed, just wait for the quota reset (24h).
